### ISSUE TITLE
Links within feeds open in same tab independently of 'Always open new tab'

### ISSUE THREAD

**Issue by StanGets** [dauphine-dev/drop-feeds#113]
Hi,

Drop Feeds 1.0 / Firefox 66.0.3 (x64) / Windows 7 (x64)

Enjoying Drop Feeds.
Issue with links within feeds that will open in the same tab (that of Drop Feeds) independently of:
`Options / Contents area / Always open new tab : checked`
I also have,
`Options / Contents area / Reuse Drop Feeds tab : checked`
but that has nothing to do with it. Unchecked to be sure, same issue.

Thanks!

**Comment by dauphine-dev** [comment]
Yes this option doesn't manage links inside feeds.
It manages what happens when you click a feed link in the tree view.

**Comment by StanGets** [comment]
@dauphine-dev , I'm surprised by your promptitude to close this thread without any other explanation than confirming what the option performs. The question is not about the option but about why a link that should open in a new tab does not _despite_ the option.

With such a rude attitude I'm bound to return to _Feedbro_. Be educated my friend.

**Comment by dauphine-dev** [comment]
Sorry if I have  been rude.

Like I said this option is about what happens when you click on a feed in tree view: if the render view will be open in a new tab or not, it has no impact on links inside the feed (in the articles).
(Then no issue here, then I have closed the issue)
Links in articles are content provide by the feed provider, and they can designed to open link in new tab or not..., but you can use the middle click to force Firefox to open them in new tab.

I will think if can force link in article in new tab in a future version.
