### ISSUE TITLE
[Bug] Items entry are duplicated

### ISSUE THREAD

**Issue by francoisunix** [dauphine-dev/drop-feeds#132]
Hello I'm Francois, I'm part of the Humanoid Team the publisher of Numerama.com. One of our user use Feed Drops to follow our website and tell us there's a problem with Numerama's feed.  

#### System: 
Windows 10 64 bits
Firefox 91.0
Drop Feeds version : 1.0.11

#### Steps to reproduce:
Add feed https://www.numerama.com/feed/ 
#### What should happen:
1 entry per item
#### What actually happened:
There's 2 entry per item
![image](https://user-images.githubusercontent.com/12845877/131371659-6f045117-d85d-4bbd-927e-bb55847f272e.png)

**Comment by dauphine-dev** [comment]
Hi @francoisunix
Thank you for report :-)

I am a Numerama reader too, then I am already know it.
It happens because the guid of the article "Gmail : comment annuler l'envoi d'un mail" is empty, and it missing up my items management, I am looking for a fix, I think I will publish a fixed version today.

**Comment by francoisunix** [comment]
Hi @dauphine-dev,
Thanks for your reply. Happy to know you are a Numerama Reader, thank you.
Thanks for the explanation and the fix.

Have a great day

Cheers

François

**Comment by dauphine-dev** [comment]
The fix (version 1.0.12.0) is available on AMO (Addons.mozilla.org)

Best,
David.
