### ISSUE TITLE
Drop feed icon is missing in Firefox

### ISSUE THREAD

**Issue by runetek2** [dauphine-dev/drop-feeds#149]
Hello,
tried to install on various computers and the green icon of Drop Feeds is hidden and cannot be showed as I can see. On older versions it was normally added to panel, now I must open Drop Feeds window via Ctrl+Shift+U.

Please, is there any way how to return/add the green icon back on panel between favourites icons?

Thank you!
Milo

**Comment by dauphine-dev** [comment]
@runetek2 Thank you for reporting this issue.
I will take a look next week (this week I am afk).

**Comment by dauphine-dev** [comment]
I have a took a look, It is the  new Firefox behavior since version 109 extensions icons are placed under the "extensions button".
![image](https://github.com/dauphine-dev/drop-feeds/assets/36274213/26ed7cea-06fb-4f2e-b812-f6f9c5709647)

You can click on the gear button then select "Pin to Toolbar" to have the Drop feeds button back.
![image](https://github.com/dauphine-dev/drop-feeds/assets/36274213/4e3b97b8-8650-4362-b151-7db2540d3c90)

More information here: 
https://support.mozilla.org/en-US/kb/extensions-button

It is the  new Firefox behavior, nothing I can do in Drop feeds, then I close this issue.
