### ISSUE TITLE
0.9.1 Weird Behavior In Feed List

### ISSUE THREAD

**Issue by thieleke** [dauphine-dev/drop-feeds#70]
@dauphine-dev 

After installing 0.9.1 from addons.mozilla.org I noticed that the feed list appears to be broken if you are using subfolders and have the "Do not display root folder" option checked.  

My "Sage Feeds" root folder in this screenshot actually has 6 subfolders (and no feeds outside of the subfolders) but only the first is shown:

![screen shot 2018-11-27 at 8 21 33 am](https://user-images.githubusercontent.com/3139346/49087791-7f637d00-f21d-11e8-835e-4c97ea24c8b2.png)

Note the Feed Item List, which I do not have activated, also apparently covering up part of the feed list.  Closing and reopening Drop Feeds appears to reset that but not the folder issue.

**Comment by dauphine-dev** [comment]
I use this option too, and I don't have this issue, but I think I know how why.
I have just committed a fix, please can you do a test with the last 0.9.1 code and tell me if it is ok ?

**Comment by dauphine-dev** [comment]
Any way I will make this fix public now because it a very big issue hopping that it is fixed, and if is not  then will do a new version again.
Please keep me inform if it is fixed or not.

**Comment by dauphine-dev** [comment]
(I answer to https://github.com/dauphine-dev/drop-feeds/issues/71#issuecomment-442147984 here)
And about this one ?

**Comment by thieleke** [comment]
I'm not able to test on my original computer until later today, but on another macOS computer 0.9.1a is displaying subfolders correctly.

The only weirdness that I noticed is if you modify the feed tree in any way (subscribing to a new feed or deleting an existing feed) causes the Feed Item List thing from above to appear until you close and reopen Drop Feeds.

**Comment by Judy85** [comment]
I noticed this as well. This is fixed for me in 0.9.1a

**Comment by dauphine-dev** [comment]
Thank you @Judy85 ;-)
I close the issue

**Comment by fcktrmp** [comment]
Here's another "weird behavior" report: since version 0.9.1a, using the "traditional" 2-row ("Sage" - feeds on top, entries at the bottom) layout doesn't work anymore. I don't want a third row for the content, I want the content to be shown in the main window when I click on an entry in the 2nd row.

I tried fiddling with the various options, but the only thing that works at all is to enable the third row ("render selected item..."), then click on an entry, then go to the render row and click on the entry again; that will open the entry in the main window. 

If I uncheck "render selected item", then nothing happens at all when clicking on the item. However, I'm expecting the item to open in the main window, as version 0.9a did. I'm downgrading to 0.9a for now...

**Comment by fcktrmp** [comment]
Oops... yeah, maybe I should have created a separate issue right away. Anyway, thanks for looking into it! :)
