### ISSUE TITLE
I have to click twice on the icon to display the panel

### ISSUE THREAD

**Issue by Machou** [dauphine-dev/drop-feeds#91]
Hello,

I have a problem on Firefox 64.0 - 64 bit - Windows 7 and the latest version of drop-feeds.

I have to click twice on the icon to display the panel. Once it's loaded, I click once and that's it.

Can you fix the bug?

Thank you. Thank you.

**Comment by dauphine-dev** [comment]
Hi @Machou,
sorry for the delay, I was AFK.
It is a know issue, last time I have saw, it was no possible to fix it, but I take a look with new API and a fresh point of view, to see if I can fix it this time.

**Comment by Machou** [comment]
Ok, maybe you can check with uBlock or other it work ;)

**Comment by dauphine-dev** [comment]
It is not so simple, uBlock or other work with an action page, not with the side bar, the limitation is for the sidebar.

A bug is open on bugzilla to add this feature.
https://bugzilla.mozilla.org/show_bug.cgi?id=1453355

Any way in the meantime, I have found a workaround, it is fixed in 0.9.4alpha1, available [here](https://github.com/dauphine-dev/drop-feeds/releases). It will be available on AMO when 0.9.4 will be ready. 

If the feature is added on a next Firefox version, I will update my code.

**Comment by dauphine-dev** [comment]
-> https://github.com/dauphine-dev/drop-feeds/issues/32
